# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjN9pNh-lYaoyMG5M_3VK16M3Mjofvg2
"""

import torch
import torch.nn as nn
import numpy as np

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class convert(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.Wq= nn.Parameter(torch.randn(dim,dim,device=device)* np.sqrt(2.0/(dim)))
        self.Wk= nn.Parameter(torch.randn(dim,dim,device=device)* np.sqrt(2.0/(dim)))
        self.Wv= nn.Parameter(torch.randn(dim,dim,device=device)* np.sqrt(2.0/(dim)))

    def forward(self, X):
        Q_list= [self.Wq@(x.T) for x in X]
        Q= torch.stack(Q_list)
        K_list= [self.Wk@(x.T) for x in X]
        K= torch.stack(K_list)
        V_list= [self.Wv@(x.T) for x in X]
        V= torch.stack(V_list)

        return Q,K,V

class FFN(nn.Module):
    def __init__(self, dim):
        super().__init__()
        d_ff= 4*dim
        self.W_a= nn.Parameter(torch.randn(dim, d_ff,device=device)*np.sqrt(2.0/dim))
        self.W_b= nn.Parameter(torch.randn(d_ff, dim,device=device)*np.sqrt(2.0/d_ff))
        self.B_a= nn.Parameter(torch.randn(d_ff,device=device))
        self.B_b= nn.Parameter(torch.randn(dim,device=device))
        self.gelu= nn.GELU()

    def forward(self, x):
        temp1= (x@self.W_a) + self.B_a
        temp2= self.gelu(temp1)
        temp3= (temp2@self.W_b) + self.B_b
        return temp3

def LayerNorm(x):
    # shape (B, T, dim)
    fac= 1e-5
    mean= torch.mean(x, dim= -1, keepdim=True)
    var= torch.std(x, dim=-1, correction=False, keepdim=True)

    std= (var+fac)**0.5
    x_norm= (x-mean)/std

    return x_norm

def fn_even(j,i,emb_dim):
    temp= j/(10000**((2*i)/emb_dim))
    return np.sin(temp)

def fn_odd(j,i,emb_dim):
    temp= j/(10000**((2*i - 1)/emb_dim))
    return np.cos(temp)

def pos_enc(T,emb_dim):

    pos_encoding= torch.zeros(T,emb_dim, device=device)

    for j in range(T):
        for i in range(emb_dim):
            # check even odd
            if(i&1):
                pos_encoding[j][i]= fn_odd(j,i)
            else:
                pos_encoding[j][i]= fn_even(j,i)


    return pos_encoding

def count_non_embedding_params(model):
    return sum(p.numel() for name, p in model.named_parameters() if 'embed' not in name and 'lm_head' not in name)

class decoder_model(nn.Module):
    def __init__(self, num_layers, vocab_size, emb_dim, T, heads):

        super(decoder_model, self).__init__()
        self.embedding = nn.Parameter(torch.randn(vocab_size,emb_dim)/(emb_dim**0.5))
        self.heads= heads
        self.num_layers = num_layers

        self.pos_encoding= pos_enc(T,emb_dim)
        # self.conv= convert(emb_dim)
        # self.ffn= FFN(emb_dim)

        tempo_1 = []
        for _ in range(num_layers):
            tempo_1.append(convert(emb_dim))
        self.convs = nn.ModuleList(tempo_1)

        tempo_2 = []
        for _ in range(num_layers):
            tempo_2.append(FFN(emb_dim))
        self.ffns = nn.ModuleList(tempo_2)


        # making the masking matrix
        self.M= torch.zeros(T,T,device=device)
        for i in range(T):
            for j in range(T):
                if(i<j):
                    self.M[i][j]= float('-inf')

        # self.dropout = nn.Dropout(0.2)

    def forward(self,x):

        x= self.embedding[x]
        # shape (B, T, Dim)

        x= x+ self.pos_encoding
        # Pre layer Normalization

        for layer in range(self.num_layers):
            x_ln= LayerNorm(x)
            # -------------------STEP 4 DONE----------------------

            Q,K,V= self.convs[layer].forward(x_ln)
            # shape (B, Dim, T)

            batch_size= x.shape[0]
            T= x.shape[1]
            dimension= x.shape[2]
            d_block= (int)(dimension/self.heads)

            Q= torch.reshape(Q, (batch_size, self.heads, d_block, T))
            K= torch.reshape(K, (batch_size, self.heads, d_block, T))
            V= torch.reshape(V, (batch_size, self.heads, d_block, T))
            # shape (B, H, D, T)

            div= d_block**0.5

            z_list= []
            for i in range(self.heads):
                q= Q[:,i,:,:]
                k= K[:,i,:,:]
                v= V[:,i,:,:]

                temp1= torch.matmul(q.transpose(1,2),k)
                temp2= temp1 / div
                temp3= torch.softmax(temp2 + self.M, dim=-1)
                temp4= torch.matmul(temp3, v.transpose(1,2))
                z_list.append(temp4)

            z_temp1= torch.cat(z_list, dim=-1)
            # shape (B, T, Dim)

            z_temp1= x+ z_temp1
            # ---------------STEP 1 ENDS HERE--------------------

            z_ln_temp1= LayerNorm(z_temp1)
            x= z_temp1 + self.ffns[layer].forward(z_ln_temp1)
            # ---------------STEP 2 ENDS HERE--------------------
            # ---------------STEP 3 ENDS HERE--------------------

        z= x@((self.embedding).T)
        # ---------------STEP 5 ENDS HERE--------------------
        return z



