# -*- coding: utf-8 -*-
"""plot_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA99EyKUBfncKweQUDw5FnhrBeVNzVyl
"""

import numpy as np
import matplotlib.pyplot as plt

# I am hardcoding the values from my original notebook
Ld_values= [1.8329036322182934, 2.079674657012211, 2.2806164638416186, 2.4399260035734742]
D_values= [1003854, 501927, 250963, 100385]

L_values= [2.0652303232809786, 1.8329036322182934, 1.5966370421075629]
N_values= [90752, 723456, 4333056]

log_Ld= np.log(Ld_values)
log_D= np.log(D_values)

slope,intercept = np.polyfit(log_D,log_Ld,1)

alpha_d= -slope
y_fit= -alpha_d*log_D + intercept

plt.scatter(log_D, log_Ld, label="Measured Models")
plt.plot(log_D, y_fit, label="Regression best fit Line")

plt.xlabel("log(D)")
plt.ylabel("log(Validation Loss)")
plt.title("Data Scaling Law")

plt.legend()
plt.savefig("data_scaling_laws.png")
plt.show()

log_L= np.log(L_values)
log_N= np.log(N_values)

slope,intercept = np.polyfit(log_N,log_L,1)

alpha_n= -slope
y_fit= -alpha_n*log_N + intercept

plt.scatter(log_N, log_L, label="Measured Models")
plt.plot(log_N, y_fit, label="Regression best fit Line")

plt.xlabel("log(N)")
plt.ylabel("log(Validation Loss)")
plt.title("Parameter Scaling Law")

plt.legend()
plt.savefig("scaling_laws.png")
plt.show()

gamma= alpha_n/alpha_d

gamma

alpha_n

alpha_d

