# -*- coding: utf-8 -*-
"""train_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaHfCclRlWxXERABc0FW9ceOk2iP6ZFq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from models import decoder_model, count_non_embedding_params

with open("/kaggle/input/datasets/kaushaltiwari/tiny-shakespeare/tiny-shakespeare.txt", "r", encoding="utf-8") as f:
    corpus = f.read()

chars = sorted(list(set(corpus)))
vocab_size = len(chars)
print(vocab_size)

char_to_idx = {ch:i for i,ch in enumerate(chars)}
idx_to_char = {i:ch for i,ch in enumerate(chars)}

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader, Dataset

tokenized_corpus= [char_to_idx[ch] for ch in corpus]
tokenized_corpus= torch.tensor(tokenized_corpus, dtype= torch.long)

len_fac= (int)(0.9*len(tokenized_corpus))
train_corpus= tokenized_corpus[:len_fac]
validation_corpus= tokenized_corpus[len_fac:]

D_100= len(train_corpus)
D_50= (int)(0.5* D_100)
D_25= (int)(0.25* D_100)
D_10= (int)(0.1* D_100)


# for 50
train_corpus_50= train_corpus[:D_50]

# for 25
train_corpus_25= train_corpus[:D_25]

# for 10
train_corpus_10= train_corpus[:D_10]

validation_corpus.shape

tokenized_corpus.shape # = len(corpus)

# create a custom dataset for this tinyShakes dataset
class CustomDataset(Dataset):

    def __init__(self, tokens, T):
        self.tokens = tokens
        self.T = T

    def __len__(self):
        return len(self.tokens) - self.T

    def __getitem__(self, idx):

        x = self.tokens[idx:idx+self.T]
        y = self.tokens[idx+1:idx+self.T+1]

        return x, y

batch_size=128
T= 256 # context
# data loader
dataset= CustomDataset(train_corpus_10, T)
validation_dataset= CustomDataset(validation_corpus, T)
loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

val_loader= DataLoader(validation_dataset, batch_size= 64, shuffle=False)

for x,y in loader:

    print(x.shape)
    break

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
loss_hist= []
val_loss_hist= []
criterion = nn.CrossEntropyLoss()

emb_dim= 128
heads= 4
num_layers= 4
model= decoder_model(num_layers, vocab_size, emb_dim, T, heads).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.0005)

N= count_non_embedding_params(model)

print(N)



def validate(model, loader):

    num_batches= 0
    total_loss=0
    model.eval()

    with torch.no_grad():
        for x,y in loader:
            x_input= x.to(device)
            y_input= y.reshape(-1).to(device)
            outputs= model(x_input)
            preds= outputs.reshape(-1, outputs.shape[-1])

            loss= criterion(preds, y_input)
            total_loss+= loss.item()

            num_batches+=1

    val_loss_hist.append(total_loss/num_batches)
    return total_loss/num_batches

def train(model, dataloader, epochs=10):

    steps= 0
    total_loss=0
    best_val_loss= 1e4
    model.train()

    for epoch in range(epochs):
        for x,y in dataloader:

            x_input= x.to(device)
            y_input= y.reshape(-1).to(device)

            optimizer.zero_grad()
            outputs = model(x_input)
            outputs = outputs.reshape(-1, outputs.shape[-1])

            loss = criterion(outputs, y_input)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            total_loss = loss.item()

            if(steps%200==0):
                print(f"Operation {steps+1}, Loss: {total_loss}")
            loss_hist.append(total_loss)

            if(steps%300 == 0):
                val_loss= validate(model,val_loader)
                best_val_loss= min(val_loss, best_val_loss)

            steps +=1

            if(steps >=3000):
                break
        if(steps >=3000):
            break

    torch.save(model.state_dict(),f'model_step{steps+1}.pth')
    return best_val_loss

best_val_loss= train(model, loader, 10)

